
# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
destination:      build
url:              https://tumblrcommunity.github.io/
encoding:         UTF-8

gems:
#  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

# Social
title: Computer Science Side of Tumblr
description: A Portal to the projects of the Computer Science Side of Tumblr 

# SEO
logo:   /assets/images/logos/logo.jpg
image:  /assets/images/logos/logo.jpg
